server:
    port: 8081
    servlet:
        context-path: /example
    tomcat:
        basedir: /apps/svr/example
        uri-encoding: utf-8
        threads:
            max: 200
spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    profiles:
        active: prod
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
